### PR TITLE
Cleaned up, updated and reworked code

### PR DESCRIPTION
**Pull request by DrMattChristian**
Julien,
I updated lasso-check.sh to use curl if wget isn't installed and download via https (SSL/TLS).
I updated rbl-check.sh script to bring shell syntax up to date, remove old/dead DNSbls and add new ones.
I updated postscreen-stats.py Python to auto-detect GeoIP modules,remove old/dead hostip.info API, fix Python PEP8 warnings, only import modules needed now, update URLs.
I added a basic Makefile to support make check, clean, compile and install.
I added setup.cfg file to allow flake8, pep8 to ignore long lines in Python code.
Thank you,
Matt

### CODE REVIEW

**Comment by jvehent** [comment]
Woa! That's quite the effort. I'll be honest: I haven't looked at this script in years, and I don't use it anymore. I'm glad it was useful to you, and I thank you for the rewrite, but I'm not in a position to test it right now.

I'm happy to just merge the patches if you're confident they work. Please confirm you've tested them on recent logs. And Thank You!

**Comment by DrMattChristian** [comment]
Julien,
Yes, it was a week-long on-off cleanup effort. Thankfully I was aided by multiple automated tools and verification methods.

To answer your question, yes I've tested Postscreen-Stats.py to the best of my ability on current maillog files generated by Postfix 2.10.1 and Python 2.7.5 from RHEL/OL 7.2. I'm also using several of the DNSbl/RBL shell scripts daily in production, which replaced my own custom work.

You're welcome! I hope my cleanup efforts benefit the larger Postfix and open source/free software community.

**Comment by jvehent** [comment]
Thanks a lot for your patch! 👍

**Comment by extremeshok** [comment]
several of the DNSbl/RBL shell scripts, curious as to which ones.

__________________________________.    https://eXtremeSHOK.com     .__________________________________

**Comment by DrMattChristian** [comment]
@extremeshok I'm using the rbl-check.sh via cron job to email me if any server Internet DNS names are on a DNSbl.  You have to modify the SRV variable to add your own DNS names. I had previously written a custom script based on rbl check but replaced it with this one, so far so good.

**Comment by Zjemm** [comment]
How would i use this stats script in combination with journalctl? any idea's about this? I'm asking because nowaday's most log files are written to journal instead of syslog

**Comment by DrMattChristian** [comment]
@Zjemm Sorry I have no idea, I have not used the code that way. You'll have to consult your OS documentation or ask on a Stack Exchange site.

**Pull request merged**
